# 09. Missing Mail: Handling Missing Data

## Introduction

Before doing any data cleaning, we need a fast way to spot which columns are missing data—nobody wants to scroll through thousands of rows hunting for blanks!

Luckily, Pandas gives us `.info()` to inspect our data quickly. As seen in previous exercises, `.info()` provides a concise summary of which columns are complete and which ones contain missing values.

### Example Output

```text
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count   D-type
---  ------     --------------   ------
 0   username   9 non-null       object
 1   location   8 non-null       object
 2   age        7 non-null       object
 3   instagram  6 non-null       object

```

From this output, we can see that:

* The DataFrame has **9 total rows**.
* `username` has 9 non-null values (100% complete).
* `location`, `age`, and `instagram` are missing entries.

When dealing with missing data, you generally have **two main options**: drop the missing data or fill it in.

---

## Strategy 1: Remove Rows with `.dropna()`

If only a small number of rows are missing data (and those entries aren't critical to your analysis), you can drop them using `.dropna()` (*Drop Not Available*).

### 1. Drop Any Missing Rows

To remove any row that contains at least one missing value across all columns:

```python
cleaned_df = df.dropna()

```

### 2. Drop Missing Rows in Specific Columns

If you only care about missing values in specific columns, use the `subset` parameter:

```python
cleaned_df = df.dropna(subset=['username', 'location'])

```

This only removes rows where `username` or `location` are empty, keeping rows that might have missing values in other columns (like `instagram`).

---

## Strategy 2: Replace Missing Values with `.fillna()`

**Imputation** means filling in missing values with logical replacement data. The right choice depends on the nature of your dataset:

| Imputation Method | Best Used For |
| --- | --- |
| **Default String** (e.g., `'Unknown'`) | Categorical text fields where missingness is acceptable |
| **Mode** (Most common value) | Categorical or discrete data with a clear dominant value |
| **Mean / Median** | Numerical data without extreme outliers |

### Examples

#### Fill with a Default Value

```python
# Fill missing locations with 'Unknown'
df['location'] = df['location'].fillna('Unknown')

```

#### Fill with the Most Common Value (Mode)

```python
# Find the most frequent value in the column
most_common_location = df['location'].mode()[0]

# Fill missing values with the mode
df['location'] = df['location'].fillna(most_common_location)

```

#### Fill with the Column Average (Mean)

```python
# Calculate the mean of the numeric column
mean_age = df['age'].mean()

# Fill missing numerical values with the mean
df['age'] = df['age'].fillna(mean_age)

```

---

## Exercise: Missing Mail

> **The Problem:** Missing mail and lost packages are a major headache. According to the USPS, nearly **25% of delivery issues** come down to incomplete addresses.

We have a DataFrame named `addresses` containing mailing addresses in the Bay Area, but several columns have missing values.

### Your Tasks

1. **Drop all incomplete rows:** Create a new DataFrame that removes rows with missing data in *any* column.
2. **Drop by specific column:** Create a new DataFrame that removes rows missing data *only* in the `city` column.
3. **Numeric Imputation:** Impute the missing values in `zip_code` using the column **mean**.
4. **Categorical Imputation:** Impute missing values in `state` and `delivery_type` using their respective **modes** (most common values).

In [10]:
import pandas as pd

data = {
  'street': [
    '5230 Newell Road',
    '1381 9th Avenue',
    '1709 Broderick St',
    '2640 Steiner St',
    '2601 Lyon St',
    '1600 Amphitheatre Parkway',
    '7500 N Glenoaks Boulevard',
    '4501 Glencoe Avenue',
    '232 Santa Margarita Ave',
    '471 Emerson Street'
  ],
  'city': [
    'Palo Alto',
    'San Francisco',
    'San Francisco',
    'San Francisco',
    'San Francisco',
    'Mountain View',
    'Burbank',
    'Marina del Rey',
    'Menlo Park',
    None
  ],
  'state': [
    'CA',
    'CA',
    'CA',
    'CA',
    'NY',
    'CA',
    'CA',
    'LA',
    None,
    None
  ],
  'zip_code': [
    94303,
    94122,
    94115,
    94123,
    94123,
    94043,
    91504,
    90292,
    94025,
    None
  ],
  'delivery_type': [
    'First Class',
    'Standard',
    'Priority',
    'Standard',
    None,
    'Expresss',
    'Standard',
    'Standard',
    None,
    None
  ]
}

addresses = pd.DataFrame(data)
addresses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   street         10 non-null     object
 1   city           9 non-null      object
 2   state          8 non-null      object
 3   zip_code       9 non-null      float64
 4   delivery_type  7 non-null      object
dtypes: float64(1), object(4)
memory usage: 532.0+ bytes

In [11]:
clean_addresses = addresses.dropna()
clean_addresses

                      street            city state  zip_code delivery_type
0           5230 Newell Road       Palo Alto    CA   94303.0   First Class
1            1381 9th Avenue   San Francisco    CA   94122.0      Standard
2          1709 Broderick St   San Francisco    CA   94115.0      Priority
3            2640 Steiner St   San Francisco    CA   94123.0      Standard
5  1600 Amphitheatre Parkway   Mountain View    CA   94043.0      Expresss
6  7500 N Glenoaks Boulevard         Burbank    CA   91504.0      Standard
7        4501 Glencoe Avenue  Marina del Rey    LA   90292.0      Standard

In [12]:
addresses_clean_city = addresses.dropna(subset=['city'])
addresses_clean_city

                      street            city state  zip_code delivery_type
0           5230 Newell Road       Palo Alto    CA   94303.0   First Class
1            1381 9th Avenue   San Francisco    CA   94122.0      Standard
2          1709 Broderick St   San Francisco    CA   94115.0      Priority
3            2640 Steiner St   San Francisco    CA   94123.0      Standard
4               2601 Lyon St   San Francisco    NY   94123.0          None
5  1600 Amphitheatre Parkway   Mountain View    CA   94043.0      Expresss
6  7500 N Glenoaks Boulevard         Burbank    CA   91504.0      Standard
7        4501 Glencoe Avenue  Marina del Rey    LA   90292.0      Standard
8    232 Santa Margarita Ave      Menlo Park  None   94025.0          None

In [13]:
avg_zip_code = addresses['zip_code'].mean()
addresses['zip_code'] = addresses['zip_code'].fillna(avg_zip_code)
addresses

                      street            city state      zip_code delivery_type
0           5230 Newell Road       Palo Alto    CA  94303.000000   First Class
1            1381 9th Avenue   San Francisco    CA  94122.000000      Standard
2          1709 Broderick St   San Francisco    CA  94115.000000      Priority
3            2640 Steiner St   San Francisco    CA  94123.000000      Standard
4               2601 Lyon St   San Francisco    NY  94123.000000          None
5  1600 Amphitheatre Parkway   Mountain View    CA  94043.000000      Expresss
6  7500 N Glenoaks Boulevard         Burbank    CA  91504.000000      Standard
7        4501 Glencoe Avenue  Marina del Rey    LA  90292.000000      Standard
8    232 Santa Margarita Ave      Menlo Park  None  94025.000000          None
9         471 Emerson Street            None  None  93405.555556          None

In [14]:
most_common_state = addresses['state'].mode()[0]
print(most_common_state)

addresses['state'] = addresses['state'].fillna(most_common_state)
addresses

CA

                      street            city state      zip_code delivery_type
0           5230 Newell Road       Palo Alto    CA  94303.000000   First Class
1            1381 9th Avenue   San Francisco    CA  94122.000000      Standard
2          1709 Broderick St   San Francisco    CA  94115.000000      Priority
3            2640 Steiner St   San Francisco    CA  94123.000000      Standard
4               2601 Lyon St   San Francisco    NY  94123.000000          None
5  1600 Amphitheatre Parkway   Mountain View    CA  94043.000000      Expresss
6  7500 N Glenoaks Boulevard         Burbank    CA  91504.000000      Standard
7        4501 Glencoe Avenue  Marina del Rey    LA  90292.000000      Standard
8    232 Santa Margarita Ave      Menlo Park    CA  94025.000000          None
9         471 Emerson Street            None    CA  93405.555556          None

In [15]:
most_common_delivery = addresses["delivery_type"].mode().iloc[0]
print(most_common_delivery)

addresses["delivery_type"] = addresses["delivery_type"].fillna(most_common_delivery)
addresses

Standard

                      street            city state      zip_code delivery_type
0           5230 Newell Road       Palo Alto    CA  94303.000000   First Class
1            1381 9th Avenue   San Francisco    CA  94122.000000      Standard
2          1709 Broderick St   San Francisco    CA  94115.000000      Priority
3            2640 Steiner St   San Francisco    CA  94123.000000      Standard
4               2601 Lyon St   San Francisco    NY  94123.000000      Standard
5  1600 Amphitheatre Parkway   Mountain View    CA  94043.000000      Expresss
6  7500 N Glenoaks Boulevard         Burbank    CA  91504.000000      Standard
7        4501 Glencoe Avenue  Marina del Rey    LA  90292.000000      Standard
8    232 Santa Margarita Ave      Menlo Park    CA  94025.000000      Standard
9         471 Emerson Street            None    CA  93405.555556      Standard