# 11. Something's Fishy: Wrong Data Types

## Introduction

When you import data into Pandas, it makes its best guess about each column's data type. Sometimes, it guesses wrong—interpreting numbers or booleans (`True`/`False`) as plain text (`object`).

This becomes a major roadblock when you try to perform mathematical operations or calculations on numeric values that Pandas is treating as strings, resulting in errors or unexpected behavior.

Luckily, Pandas makes it easy to inspect and convert data types.

---

## 1. Inspecting Data Types with `.dtypes`

To check the data type of every column in your DataFrame, use the `.dtypes` attribute:

```python
df.dtypes

```

### Example Output

```text
username     object
location     object
age           int64
instagram    object
dtype: object

```

In this output:

* `age` is stored as `int64` (Pandas treats it as an integer, allowing math operations).
* `username`, `location`, and `instagram` are `object` types (typically text/strings).

---

## 2. Changing Data Types with `pd.to_numeric()`

If Pandas imports a numeric column as text, you can convert it using `pd.to_numeric()`:

```python
df['age'] = pd.to_numeric(df['age'])

```

### Handling Bad Inputs with `errors='coerce'`

Standard conversion only works if **every single value** in the column can be converted to a number. If a row contains text like `'twenty years old'` or invalid characters, Pandas will throw a `ValueError`.

To safely convert messy columns without crashing your code, use the `errors='coerce'` parameter:

```python
df['age'] = pd.to_numeric(df['age'], errors='coerce')

```

> **How `errors='coerce'` works:** Instead of throwing an error when encountering non-convertible text, Pandas replaces those invalid values with `NaN` (*Not a Number*). You can then use `.dropna()` or `.fillna()` to clean up those missing values.

---

## Exercise: Something's Fishy...

> 🐟 **The Scenario:** You've been given a DataFrame named `high_scores` containing high scores and playtimes for players in an online game. However, some values aren't formatted consistently, hiding errors or suspicious entries.

### Your Tasks

1. **Inspect types:** Check the data types of the `high_scores` DataFrame using `.dtypes`.
2. **Convert columns:** Use `pd.to_numeric()` with `errors='coerce'` to safely convert the score and time-played columns into numeric types.
3. **Clean invalid values:** Clean up any `NaN` values generated during the conversion process.
4. **Calculate statistics:** Find the average (`.mean()`) for both high scores and time played.

In [2]:
import pandas as pd

data = {
    "player_name": [
        "Parzival",
        "Ar3mis",
        "Aech",
        "Kirito",
        "Azuna",
        "nakedinthewoods",
        "Sonny666",
        "X.X",
        "Fendi_Gucci",
        "Professor Chaos",
    ],
    "score": [
        "1500",
        "2300",
        "1800",
        "2,100",
        "1700",
        "2000",
        "2200",
        "1600",
        "1900",
        "2k50",
    ],
    "level": [12, 15, 13, 14, 12, 13, 15, 11, 14, 13],
    "time_solved": [
        "23.5",
        "35.2",
        "19.0",
        "14.8",
        "3.8",
        "42.5",
        "5h",
        "33.2",
        "4.3",
        "24.6",
    ],
}

high_scores = pd.DataFrame(data)
high_scores

       player_name  score  level time_solved
0         Parzival   1500     12        23.5
1           Ar3mis   2300     15        35.2
2             Aech   1800     13        19.0
3           Kirito  2,100     14        14.8
4            Azuna   1700     12         3.8
5  nakedinthewoods   2000     13        42.5
6         Sonny666   2200     15          5h
7              X.X   1600     11        33.2
8      Fendi_Gucci   1900     14         4.3
9  Professor Chaos   2k50     13        24.6

In [3]:
high_scores.dtypes

player_name    object
score          object
level           int64
time_solved    object
dtype: object

In [5]:
high_scores['time_solved'] = pd.to_numeric(high_scores['time_solved'], errors = 'coerce')
high_scores

       player_name  score  level  time_solved
0         Parzival   1500     12         23.5
1           Ar3mis   2300     15         35.2
2             Aech   1800     13         19.0
3           Kirito  2,100     14         14.8
4            Azuna   1700     12          3.8
5  nakedinthewoods   2000     13         42.5
6         Sonny666   2200     15          NaN
7              X.X   1600     11         33.2
8      Fendi_Gucci   1900     14          4.3
9  Professor Chaos   2k50     13         24.6

In [10]:
avg_time_solved = round(high_scores['time_solved'].mean(), 2)
print(avg_time_solved)

high_scores['time_solved'] = high_scores['time_solved'].fillna(avg_time_solved)
high_scores

22.32

       player_name  score  level  time_solved
0         Parzival   1500     12    23.500000
1           Ar3mis   2300     15    35.200000
2             Aech   1800     13    19.000000
3           Kirito  2,100     14    14.800000
4            Azuna   1700     12     3.800000
5  nakedinthewoods   2000     13    42.500000
6         Sonny666   2200     15    22.322222
7              X.X   1600     11    33.200000
8      Fendi_Gucci   1900     14     4.300000
9  Professor Chaos   2k50     13    24.600000