# Congrats!

You've reached the end of the first chapter on Pandas and DataFrames! Nice work!

Here's a recap of the main takeaways from this chapter:

    DataFrames store data in rows and columns. They can be created from dictionaries, lists, or imported directly from files.
    Some preliminary data exploration:
        .head() shows the first few rows of the DataFrame.
        .tail() shows the last few rows of the DataFrame.
        .info() displays column names, data types, etc.
        .describe() summarizes stats for numeric columns.
    Select specific columns from a DataFrame by using square brackets [ ].
    Filter rows of DataFrames by using boolean expressions using >, <, or ==. Chain multiple boolean expressions together using AND (&) and OR (|).
    We can sort, rename, and add new columns to a DataFrame.

Let's put all of this together with one final exercise.
Instructions

# Task

It's time to let your creativity shine!

Create a DataFrame about a topic of your choice! It should have at least 10 rows × 5 columns.

Once it is created, perform the following operations:

    Add a new column
    Sort the DataFrame by a particular column
    Filter out rows based on one or more conditions

In [1]:
import pandas as pd

students_data = {
    "Name": [
        "Alex", "Maria", "Daniel", "Sofia", "Ivan",
        "Emma", "George", "Elena", "Martin", "Anna"
    ],
    "Age": [
        19, 20, 18, 21, 20,
        19, 22, 18, 21, 20
    ],
    "Major": [
        "Computer Science", "Engineering", "Mathematics", "Business", "Physics",
        "Computer Science", "Engineering", "Biology", "Mathematics", "Business"
    ],
    "Grade": [
        5.50, 5.20, 5.80, 4.90, 5.10,
        5.70, 4.80, 5.40, 5.60, 5.00
    ],
    "Passed": [
        True, True, True, True, True,
        True, True, True, True, True
    ]
}

students = pd.DataFrame(students_data)
students

     Name  Age             Major  Grade  Passed
0    Alex   19  Computer Science    5.5    True
1   Maria   20       Engineering    5.2    True
2  Daniel   18       Mathematics    5.8    True
3   Sofia   21          Business    4.9    True
4    Ivan   20           Physics    5.1    True
5    Emma   19  Computer Science    5.7    True
6  George   22       Engineering    4.8    True
7   Elena   18           Biology    5.4    True
8  Martin   21       Mathematics    5.6    True
9    Anna   20          Business    5.0    True

In [2]:
students['University'] = [
    "Technical University of Sofia",
    "Sofia University",
    "University of Oxford",
    "University of Cambridge",
    "MIT",
    "Stanford University",
    "RWTH Aachen University",
    "TU Delft",
    "ETH Zurich",
    "Technical University of Munich"
]
students

,Name,Age,Major,Grade,Passed,University
0,Alex,19,Computer Science,5.5,True,Technical University of Sofia
1,Maria,20,Engineering,5.2,True,Sofia University
2,Daniel,18,Mathematics,5.8,True,University of Oxford
3,Sofia,21,Business,4.9,True,University of Cambridge
4,Ivan,20,Physics,5.1,True,MIT
5,Emma,19,Computer Science,5.7,True,Stanford University
6,George,22,Engineering,4.8,True,RWTH Aachen University
7,Elena,18,Biology,5.4,True,TU Delft
8,Martin,21,Mathematics,5.6,True,ETH Zurich
9,Anna,20,Business,5.0,True,Technical University of Munich

In [3]:
grade_sorted = students.sort_values(by='Grade', ascending=True)
grade_sorted

,Name,Age,Major,Grade,Passed,University
6,George,22,Engineering,4.8,True,RWTH Aachen University
3,Sofia,21,Business,4.9,True,University of Cambridge
9,Anna,20,Business,5.0,True,Technical University of Munich
4,Ivan,20,Physics,5.1,True,MIT
1,Maria,20,Engineering,5.2,True,Sofia University
7,Elena,18,Biology,5.4,True,TU Delft
0,Alex,19,Computer Science,5.5,True,Technical University of Sofia
8,Martin,21,Mathematics,5.6,True,ETH Zurich
5,Emma,19,Computer Science,5.7,True,Stanford University
2,Daniel,18,Mathematics,5.8,True,University of Oxford

In [4]:
students = students.rename(columns = {'Name': 'First Name'})
students

,First Name,Age,Major,Grade,Passed,University
0,Alex,19,Computer Science,5.5,True,Technical University of Sofia
1,Maria,20,Engineering,5.2,True,Sofia University
2,Daniel,18,Mathematics,5.8,True,University of Oxford
3,Sofia,21,Business,4.9,True,University of Cambridge
4,Ivan,20,Physics,5.1,True,MIT
5,Emma,19,Computer Science,5.7,True,Stanford University
6,George,22,Engineering,4.8,True,RWTH Aachen University
7,Elena,18,Biology,5.4,True,TU Delft
8,Martin,21,Mathematics,5.6,True,ETH Zurich
9,Anna,20,Business,5.0,True,Technical University of Munich

In [5]:
honors_student = students[students['Grade'] >= 5.5]
honors_student

,First Name,Age,Major,Grade,Passed,University
0,Alex,19,Computer Science,5.5,True,Technical University of Sofia
2,Daniel,18,Mathematics,5.8,True,University of Oxford
5,Emma,19,Computer Science,5.7,True,Stanford University
8,Martin,21,Mathematics,5.6,True,ETH Zurich

In [6]:
matches = pd.read_csv('matches_clean.csv')
matches

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,result,is_competitive,home_rank,home_rank_points,away_rank,away_rank_points
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False,D,0,211.0,0.00,211.0,0.00
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False,H,0,211.0,0.00,211.0,0.00
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False,H,0,211.0,0.00,211.0,0.00
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False,D,0,211.0,0.00,211.0,0.00
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False,H,0,211.0,0.00,211.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49457,2026-07-12,Argentina,Switzerland,3.0,1.0,FIFA World Cup,Unknown,World,True,H,1,1.0,1867.25,20.0,1625.16
49458,2026-07-14,France,Spain,0.0,2.0,FIFA World Cup,Unknown,World,True,A,1,2.0,1859.78,3.0,1853.27
49459,2026-07-15,England,Argentina,1.0,2.0,FIFA World Cup,Unknown,World,True,A,1,4.0,1813.81,1.0,1867.25
49460,2026-07-18,France,England,4.0,6.0,FIFA World Cup,Unknown,World,True,A,1,2.0,1859.78,4.0,1813.81
49461,2026-07-19,Spain,Argentina,1.0,0.0,FIFA World Cup,Unknown,World,True,H,1,3.0,1853.27,1.0,1867.25